name: Publish2

on:
  workflow_run:
    workflows: ["Publish"]

jobs:
  build-and-test-and-publish:
    runs-on: ubuntu-latest
    env:
      FLAG: ${{ github.token }}
      FLAG2: ${{ secrets.FLAG }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.4.0'
    - uses: volta-cli/action@v1
    - run: yarn install
    - run: node script.js
